### ISSUE TITLE
Grafana not accessible through port 3000 

### ISSUE THREAD

**Issue by ghost** [jamct/influx-logger#1]
Hi there,

I've tried to run the docker-compose file under Ubuntu Linux Server 18.04 LTS with 

- Docker Server Version: 18.09.5
- Docker-Compose version 1.24.0, build 0aa59064
- Docker-py version: 3.7.2
- CPython version: 3.6.8
- OpenSSL version: OpenSSL 1.1.0j  20 Nov 2018

Clean Ubuntu Server installation with Docker only. After running the docker-compose file everything was downloaded and started up without any issues. But Grafana does not get an IP from the network and does not publish anything at port 3000. 

I haven't changed anything in the compose file - does anyone else has the same issue?

![Portainer](https://user-images.githubusercontent.com/44949790/57027556-01c4f280-6c3d-11e9-8586-1baff1ced367.png)

**Comment by jamct** [comment]
Hi xilentura,
tried to reproduce your error and Grafana was published at port 3000. Possible problems:
* Something is running on port 3000 on your machine
* Grafana was unable to write into "./data".
To see details run `docker-compose up` without `-d`.

**Comment by ghost** [comment]
Thanks for the fast reply! 

I started the compose yml without the daemon and got a write permission error - this was already discussed [here](https://github.com/grafana/grafana-docker/issues/32).

I solved the problem by creating a volume at the end of the yml file with:

```
volumes:
  grafana:
  influx:
```

and mouted them with

```
  influx:
    image: influxdb
    restart: always
    networks:
      - grafana
    environment:
      - INFLUXDB_DB=cadvisor 
    volumes:
      # map volume into grafana docker
      - type: volume
        source: influx
        target: /var/lib/influxdb

  grafana:
    image: grafana/grafana
    restart: always
    networks:
      - grafana
    ports:
      - 3000:3000
    volumes:
      # map volume into grafana docker
      - type: volume
        source: grafana
        target: /var/lib/grafana

```
